### ISSUE TITLE
The sources folder is missing the sources

### ISSUE THREAD

**Issue by imbur** [jerabek/ARMv7t-WCET-Analysis#1]
The README in the root says the sources folder has the OTAWA framework sources (including mkffx and oswa), but there is only a readme file. I would really appreciate it if you could add the sources or point me in a direction where I could get them (OTAWA is not an issue, but I was not able to find the mkffx and oswa sources).

Thank you!

**Comment by jerabek** [comment]
This repository was used by students to install the binaries.
Both tools might be available somewhere at UASTW embedded systems department. I’m not employed at this institution for many years and this software is not maintained, thus, i would suggest to use the regular owcet tool from the original repository on  http://otawa.fr
