### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by thedulre159** [jerabek/ARMv7t-WCET-Analysis#2]
Hi this is not issue of the code but i just wanted some information. I am trying to compute the wcet using otawa but i do not understand how you created the hardware models like cache.xml memory.xml and pipeline.xml. I am using the STM32L475 MCU the board is the B-L475E-IOT01A2. I have read that the Cortex M4 has 3 stages but i don't understand where you got all this information about the stages to model you pipeline.xml file. I don't understand how to model the memory.xml model too my reference manual is https://www.st.com/resource/en/reference_manual/dm00083560-stm32l47xxx-stm32l48xxx-stm32l49xxx-and-stm32l4axxx-advanced-armbased-32bit-mcus-stmicroelectronics.pdfBtw sorry for writing here but i had no other way to contact you.

**Comment by jerabek** [comment]
Please check the architecture documentation, which is the ARM Cortex-M4 technical reference manual in your case. The pipeline and memory are described as good as possible with the available information because you won‘t get all the mandatory insights from ARM for a full description.
